build max32666 app switcher

diff --git a/.github/workflows/maxrefdes178.yml b/.github/workflows/maxrefdes178.yml
--- a/.github/workflows/maxrefdes178.yml
+++ b/.github/workflows/maxrefdes178.yml
@@ -66,6 +66,35 @@ jobs:
           "@ | Out-File -Encoding ASCII -filepath maxrefdes178_common\maxrefdes178_build_info.h
           (Get-Content maxrefdes178_common\maxrefdes178_build_info.h -Raw).Replace("`n","`r`n") | Set-Content maxrefdes178_common\maxrefdes178_build_info.h -Force
           
+          
+      - name: Build MAX32666 Bootloader Firmware
+        run: |
+          @"
+          cd "${{github.workspace}}"
+          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
+          export FIRMWARE_PATH="`$MAXIM_PATH\Libraries"
+          export TOOLCHAIN_PATH="`$MAXIM_PATH\Tools"
+          export PATH="`$TOOLCHAIN_PATH\GNUTools\bin;`$TOOLCHAIN_PATH\MinGW\msys\1.0\bin;`$PATH"
+          
+          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
+          cd "maxrefdes178-AppSwitcher\maxrefdes178_max32666_bootloader"
+          make -r -j
+          if [ `$? -ne 0 ]; then
+            echo "BUILD IS FAILED!"
+          exit -1
+          fi
+          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
+          
+          "@ | Out-File -Encoding ASCII -filepath run_build.sh
+          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\bin"
+          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
+          if (!$?) {
+            exit -1
+          }
+          
+          mv -Force maxrefdes178-AppSwitcher\maxrefdes178_max32666_bootloader\build\maxrefdes178_max32666_bootloader.bin maxrefdes178-AppSwitcher\
+          
+          
       - name: Build FaceID MAX78000 Video Firmware
         run: |
           @"
@@ -116,31 +145,31 @@ jobs:
             exit -1
           }
           
-#      - name: Build FaceID MAX32666 Firmware
-#        run: |
-#          @"
-#          cd "${{github.workspace}}"
-#          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
-#          export FIRMWARE_PATH="`$MAXIM_PATH\Libraries"
-#          export TOOLCHAIN_PATH="`$MAXIM_PATH\Tools"
-#          export PATH="`$TOOLCHAIN_PATH\GNUTools\bin;`$TOOLCHAIN_PATH\MinGW\msys\1.0\bin;`$PATH"
-#          
-#          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
-#          cd "maxrefdes178-FaceId\maxrefdes178_max32666"
-#          make -r -j
-#          make -r -j
-#          if [ `$? -ne 0 ]; then
-#            echo "BUILD IS FAILED!"
-#          exit -1
-#          fi
-#          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
-#          
-#          "@ | Out-File -Encoding ASCII -filepath run_build.sh
-#          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\bin"
-#          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
-#          if (!$?) {
-#            exit -1
-#          }
+      - name: Build FaceID MAX32666 Firmware
+        run: |
+          @"
+          cd "${{github.workspace}}"
+          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
+          export FIRMWARE_PATH="`$MAXIM_PATH\Libraries"
+          export TOOLCHAIN_PATH="`$MAXIM_PATH\Tools"
+          export PATH="`$TOOLCHAIN_PATH\GNUTools\bin;`$TOOLCHAIN_PATH\MinGW\msys\1.0\bin;`$PATH"
+          
+          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
+          cd "maxrefdes178-FaceId\maxrefdes178_max32666"
+          make -r -j
+          make -r -j
+          if [ `$? -ne 0 ]; then
+            echo "BUILD IS FAILED!"
+          exit -1
+          fi
+          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
+          
+          "@ | Out-File -Encoding ASCII -filepath run_build.sh
+          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\bin"
+          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
+          if (!$?) {
+            exit -1
+          }
           
           
       - name: Build CatsDogs MAX78000 Video Firmware
@@ -377,23 +406,35 @@ jobs:
           
           mkdir release\FaceId
           mv maxrefdes178-FaceId\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video.bin release\FaceId\maxrefdes178_max78000_video_faceid_v${env:VERSION}.bin
+          mv maxrefdes178-FaceId\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video_app.msbl release\FaceId\maxrefdes178_max78000_video_faceid_v${env:VERSION}.msbl
           mv maxrefdes178-FaceId\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio.bin release\FaceId\maxrefdes178_max78000_audio_faceid_v${env:VERSION}.bin
-          # mv maxrefdes178-FaceId\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\FaceId\maxrefdes178_max32666_faceid_v${env:VERSION}.bin
+          mv maxrefdes178-FaceId\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio_app.msbl release\FaceId\maxrefdes178_max78000_audio_faceid_v${env:VERSION}.msbl
+          mv maxrefdes178-FaceId\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\FaceId\maxrefdes178_max32666_faceid_v${env:VERSION}.bin
+          mv maxrefdes178-FaceId\maxrefdes178_max32666\build\maxrefdes178_max32666_app.msbl release\FaceId\maxrefdes178_max32666_faceid_v${env:VERSION}.msbl
           
           mkdir release\CatsDogs
           mv maxrefdes178-CatsDogs\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video.bin release\CatsDogs\maxrefdes178_max78000_video_catsdogs_v${env:VERSION}.bin
+          mv maxrefdes178-CatsDogs\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video_app.msbl release\CatsDogs\maxrefdes178_max78000_video_catsdogs_v${env:VERSION}.msbl
           mv maxrefdes178-CatsDogs\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio.bin release\CatsDogs\maxrefdes178_max78000_audio_catsdogs_v${env:VERSION}.bin
+          mv maxrefdes178-CatsDogs\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio_app.msbl release\CatsDogs\maxrefdes178_max78000_audio_catsdogs_v${env:VERSION}.msbl
           mv maxrefdes178-CatsDogs\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\CatsDogs\maxrefdes178_max32666_catsdogs_v${env:VERSION}.bin
+          mv maxrefdes178-CatsDogs\maxrefdes178_max32666\build\maxrefdes178_max32666_app.msbl release\CatsDogs\maxrefdes178_max32666_catsdogs_v${env:VERSION}.msbl
           
           mkdir release\UNet
           mv maxrefdes178-UNet\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video.bin release\UNet\maxrefdes178_max78000_video_unet_v${env:VERSION}.bin
+          mv maxrefdes178-UNet\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video_app.msbl release\UNet\maxrefdes178_max78000_video_unet_v${env:VERSION}.msbl
           mv maxrefdes178-UNet\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio.bin release\UNet\maxrefdes178_max78000_audio_unet_v${env:VERSION}.bin
+          mv maxrefdes178-UNet\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio_app.msbl release\UNet\maxrefdes178_max78000_audio_unet_v${env:VERSION}.msbl
           mv maxrefdes178-UNet\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\UNet\maxrefdes178_max32666_unet_v${env:VERSION}.bin
+          mv maxrefdes178-UNet\maxrefdes178_max32666\build\maxrefdes178_max32666_app.msbl release\UNet\maxrefdes178_max32666_unet_v${env:VERSION}.msbl
           
           mkdir release\WildLife
           mv maxrefdes178-WildLife\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video.bin release\WildLife\maxrefdes178_max78000_video_wildlife_v${env:VERSION}.bin
+          mv maxrefdes178-WildLife\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video_app.msbl release\WildLife\maxrefdes178_max78000_video_wildlife_v${env:VERSION}.msbl
           mv maxrefdes178-WildLife\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio.bin release\WildLife\maxrefdes178_max78000_audio_wildlife_v${env:VERSION}.bin
+          mv maxrefdes178-WildLife\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio_app.msbl release\WildLife\maxrefdes178_max78000_audio_wildlife_v${env:VERSION}.msbl
           mv maxrefdes178-WildLife\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\WildLife\maxrefdes178_max32666_wildlife_v${env:VERSION}.bin
+          mv maxrefdes178-WildLife\maxrefdes178_max32666\build\maxrefdes178_max32666_app.msbl release\WildLife\maxrefdes178_max32666_wildlife_v${env:VERSION}.msbl
           
       - uses: actions/upload-artifact@v2
         if: always()
