Revert "Remove VCAudioPlayback and ASL demos"
This reverts commit 9108c1cc62d26830b7420a34d3005faf78f4f7ae.

diff --git a/.github/workflows/maxrefdes178.yml b/.github/workflows/maxrefdes178.yml
--- a/.github/workflows/maxrefdes178.yml
+++ b/.github/workflows/maxrefdes178.yml
@@ -227,6 +227,73 @@ jobs:
           }
           
           
+      - name: Build ASL MAX78000 Video Firmware
+        run: |
+          @"
+          cd "${{github.workspace}}"
+          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
+          
+          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
+          cd "maxrefdes178-ASL\maxrefdes178_max78000_video"
+          make -r -j
+          if [ `$? -ne 0 ]; then
+            echo "BUILD FAILED!"
+          exit -1
+          fi
+          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
+          
+          "@ | Out-File -Encoding ASCII -filepath run_build.sh
+          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\10.3\bin"
+          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
+          if (!$?) {
+            exit -1
+          }
+          
+      - name: Build ASL MAX78000 Audio Firmware
+        run: |
+          @"
+          cd "${{github.workspace}}"
+          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
+          
+          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
+          cd "maxrefdes178-ASL\maxrefdes178_max78000_audio"
+          make -r -j
+          if [ `$? -ne 0 ]; then
+            echo "BUILD FAILED!"
+          exit -1
+          fi
+          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
+          
+          "@ | Out-File -Encoding ASCII -filepath run_build.sh
+          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\10.3\bin"
+          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
+          if (!$?) {
+            exit -1
+          }
+          
+      - name: Build ASL MAX32666 Firmware
+        run: |
+          @"
+          cd "${{github.workspace}}"
+          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
+          
+          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
+          cd "maxrefdes178-ASL\maxrefdes178_max32666"
+          make -r -j
+          if [ `$? -ne 0 ]; then
+            echo "BUILD FAILED!"
+          exit -1
+          fi
+          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
+          
+          "@ | Out-File -Encoding ASCII -filepath run_build.sh
+          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\10.3\bin"
+          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
+          if (!$?) {
+            exit -1
+          }
+          
+          
       - name: Build UNet MAX78000 Video Firmware
         run: |
           @"
@@ -360,7 +427,72 @@ jobs:
           if (!$?) {
             exit -1
           }  
+
+      - name: Build Voice Controlled Audio Playback MAX78000 Video Firmware
+        run: |
+          @"
+          cd "${{github.workspace}}"
+          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
           
+          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
+          cd "maxrefdes178-VCAudioPlayback\maxrefdes178_max78000_video"
+          make -r -j
+          if [ `$? -ne 0 ]; then
+            echo "BUILD FAILED!"
+          exit -1
+          fi
+          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
+          
+          "@ | Out-File -Encoding ASCII -filepath run_build.sh
+          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\10.3\bin"
+          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
+          if (!$?) {
+            exit -1
+          }
+          
+      - name: Build Voice Controlled Audio Playback MAX78000 Audio Firmware
+        run: |
+          @"
+          cd "${{github.workspace}}"
+          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
+          
+          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
+          cd "maxrefdes178-VCAudioPlayback\maxrefdes178_max78000_audio"
+          make -r -j
+          if [ `$? -ne 0 ]; then
+            echo "BUILD FAILED!"
+          exit -1
+          fi
+          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
+          
+          "@ | Out-File -Encoding ASCII -filepath run_build.sh
+          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\10.3\bin"
+          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
+          if (!$?) {
+            exit -1
+          }
+          
+      - name: Build Voice Controlled Audio Playback MAX32666 Firmware
+        run: |
+          @"
+          cd "${{github.workspace}}"
+          export MAXIM_PATH="${{github.workspace}}\MaximSDK"
+          
+          echo "*-*-*-*-*-* BUILD STARTED -*-*-*-*-*-"
+          cd "maxrefdes178-VCAudioPlayback\maxrefdes178_max32666"
+          make -r -j
+          if [ `$? -ne 0 ]; then
+            echo "BUILD FAILED!"
+          exit -1
+          fi
+          echo "*-*-*-*-*-* BUILD FINISHED -*-*-*-*-*-"
+          
+          "@ | Out-File -Encoding ASCII -filepath run_build.sh
+          $env:Path += ";${{github.workspace}}\MaximSDK\Tools\GNUTools\10.3\bin"
+          ${{github.workspace}}\MaximSDK\Tools\MinGW\msys\1.0\bin\sh --login -i ${{github.workspace}}\run_build.sh
+          if (!$?) {
+            exit -1
+          }
           
       - name: Prepare Release
         run: |
@@ -384,6 +516,14 @@ jobs:
           mv maxrefdes178-CatsDogs\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\CatsDogs\maxrefdes178_max32666_catsdogs_v${env:VERSION}.bin
           mv maxrefdes178-CatsDogs\maxrefdes178_max32666\build\maxrefdes178_max32666_app.msbl release\CatsDogs\maxrefdes178_max32666_catsdogs_v${env:VERSION}.msbl
           
+          mkdir release\ASL
+          mv maxrefdes178-ASL\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video.bin release\ASL\maxrefdes178_max78000_video_asl_v${env:VERSION}.bin
+          mv maxrefdes178-ASL\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video_app.msbl release\ASL\maxrefdes178_max78000_video_asl_v${env:VERSION}.msbl
+          mv maxrefdes178-ASL\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio.bin release\ASL\maxrefdes178_max78000_audio_asl_v${env:VERSION}.bin
+          mv maxrefdes178-ASL\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio_app.msbl release\ASL\maxrefdes178_max78000_audio_asl_v${env:VERSION}.msbl
+          mv maxrefdes178-ASL\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\ASL\maxrefdes178_max32666_asl_v${env:VERSION}.bin
+          mv maxrefdes178-ASL\maxrefdes178_max32666\build\maxrefdes178_max32666_app.msbl release\ASL\maxrefdes178_max32666_asl_v${env:VERSION}.msbl
+          
           mkdir release\UNet
           mv maxrefdes178-UNet\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video.bin release\UNet\maxrefdes178_max78000_video_unet_v${env:VERSION}.bin
           mv maxrefdes178-UNet\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video_app.msbl release\UNet\maxrefdes178_max78000_video_unet_v${env:VERSION}.msbl
@@ -399,6 +539,14 @@ jobs:
           mv maxrefdes178-WildLife\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio_app.msbl release\WildLife\maxrefdes178_max78000_audio_wildlife_v${env:VERSION}.msbl
           mv maxrefdes178-WildLife\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\WildLife\maxrefdes178_max32666_wildlife_v${env:VERSION}.bin
           mv maxrefdes178-WildLife\maxrefdes178_max32666\build\maxrefdes178_max32666_app.msbl release\WildLife\maxrefdes178_max32666_wildlife_v${env:VERSION}.msbl
+          
+          mkdir release\VCAudioPlayback
+          mv maxrefdes178-VCAudioPlayback\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video.bin release\VCAudioPlayback\maxrefdes178_max78000_video_vcap_v${env:VERSION}.bin
+          mv maxrefdes178-VCAudioPlayback\maxrefdes178_max78000_video\build\maxrefdes178_max78000_video_app.msbl release\VCAudioPlayback\maxrefdes178_max78000_video_vcap_v${env:VERSION}.msbl
+          mv maxrefdes178-VCAudioPlayback\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio.bin release\VCAudioPlayback\maxrefdes178_max78000_audio_vcap_v${env:VERSION}.bin
+          mv maxrefdes178-VCAudioPlayback\maxrefdes178_max78000_audio\build\maxrefdes178_max78000_audio_app.msbl release\VCAudioPlayback\maxrefdes178_max78000_audio_vcap_v${env:VERSION}.msbl
+          mv maxrefdes178-VCAudioPlayback\maxrefdes178_max32666\build\maxrefdes178_max32666.bin release\VCAudioPlayback\maxrefdes178_max32666_vcap_v${env:VERSION}.bin
+          mv maxrefdes178-VCAudioPlayback\maxrefdes178_max32666\build\maxrefdes178_max32666_app.msbl release\VCAudioPlayback\maxrefdes178_max32666_vcap_v${env:VERSION}.msbl
           
       - uses: actions/upload-artifact@v2
         if: always()
